{% set version = "0.7.3" %}

package:
  name: towhee
  version: {{ version }}

source:
  url: https://github.com/towhee-io/towhee/releases/download/{{ version }}/towhee-{{ version }}.tar.gz
  sha256: fac7c552547ee9dc0c930454fc64c6285d7a0356b112a9823c6a60dc5b3ae342

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - pyyaml >=5.3.0
    - requests >=2.12.5
    - tqdm >=4.59.0
    - pytorch >=1.8.0
    - ruamel.yaml <=0.16.6
    - tabulate
    - numpy >=1.19.5
    - git

test:
  commands:
    - pip check
  requires:
    - pip
    - pytorch >=1.8.0
    - torchvision >=0.9.0
    - numpy >=1.19.5
    - pandas >=1.1.5
    - requests >=2.12.5
    - tqdm >=4.59.0
    - pillow >=8.3.1
    - scipy >=1.5.3
    - opencv >=4.5.3.56 # rename from opencv-python
    - torchmetrics >=0.7.0
    - ruamel.yaml <=0.16.6
    - matplotlib >=3.0.0
    - importlib_metadata
    - tabulate
    - ipython
    - scikit-learn
    - pydeprecate
    - setuptools_scm

about:
  home: https://github.com/towhee-io/towhee
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Towhee is a flexible, application-oriented framework for computing embedding vectors over unstructured data.
  doc_url: https://docs.towhee.io/
  dev_url: https://docs.towhee.io/advanced/contributing-guide
  description: |
    For win-64 users, you need to run `conda config --add channels 'pytorch'` first due to this [issue about pytorch](https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32).

    [Towhee](https://towhee.io/) is a flexible, application-oriented framework for computing embedding vectors over unstructured data. 
    It aims to make democratize anything2vec, allowing everyone - from beginner developers to large organizations - 
    to train and deploy complex machine learning pipelines with just a few lines of code.
    Towhee has pre-built pipelines for a variety of tasks, including audio/music embeddings, image embeddings, celebrity recognition, and more. 
    For a full list of pipelines, feel free to visit our [Towhee hub](https://hub.towhee.io/).

extra:
  recipe-maintainers:
    - chiiizzzy
    - haorenfsa
